---

- name: Configure apache document root folder in Ubuntu
  copy: 
     src: 000-default.conf 
     dest: /etc/apache2/sites-available/000-default.conf 
     backup: yes
  notify:
     - Restart apache2 service in Ubuntu

- name: Grant permission to document root folder in Ubuntu
  copy: 
      src: apache2.conf 
      dest: /etc/apache2/apache2.conf
  notify:
     - Restart apache2 service in Ubuntu

...